//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SundayGolf.Models
{
    public partial class Golfer
    {
        public Golfer()
        {
            this.Weekly = new HashSet<Weekly>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int GolferID { get; set; }
        public string GolferName { get; set; }
    
        public virtual ICollection<Weekly> Weekly { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
    
}
