//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SundayGolf.Models
{
    public partial class Schedule
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int GolferID { get; set; }
        public int CourseID { get; set; }
        public Nullable<int> Golfing { get; set; }
        public Nullable<int> NotGolfing { get; set; }
        public Nullable<int> Maybe { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Golfer Golfer { get; set; }
    }
    
}
